config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'pages#home'
  get 'membership', to: 'pages#membership'
  get 'contact', to: 'pages#contact'
  get 'cookie_consent', to: 'pages#cookie_consent'
  get 'pricing', to: 'pages#pricing'

  namespace :admin do
    resources :bets, except: %i[show]
    post 'bets/matches_autocomplete', to: 'bets#matches_autocomplete'
    post 'bets/:id/matches_autocomplete', to: 'bets#matches_autocomplete'
    patch 'bet_won', to: 'bets#bet_won', as: :bet_won
    post 'bets/:id/edit-bet-data', to: 'bets#edit_bet_data'
    post 'bets/send-daily-picks', to: 'bets#send_daily_picks'
    patch 'bets/:id/unlock_pick', to: 'bets#unlock_pick', as: :unlock_bet
  end

  namespace :stripe do
    get 'checkout', to: 'checkout#new'
    post 'get-client-secret', to: 'checkout#send_client_secret'
    get 'success', to: 'checkout#success'
    post 'subscribe-customer', to: 'checkout#create_subscription'
    post 'webhook', to: 'webhook#handle_webhook'
    post 'update-payment-method', to: 'checkout#update_payment_method'
  end

  namespace :postmark do
    post 'webhook', to: 'webhook#handle_webhook'
  end
end

app/views/shared/_admin_buttons.html.erb
<div class="c-bet-card__buttons-grid">
  <%= button_to admin_bet_path(bet.id), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete, class: "c-button--danger-outline c-bet-card__button" do %>
    <%= icon('fa-solid', 'trash') %>
  <% end %>

  <%= button_to edit_admin_bet_path(bet.id), method: :get, class: "c-button--warning-outline c-bet-card__button" do %>
    <%= icon('fa-solid', 'pencil') %>
  <% end %>

  <%= button_to 'Win', admin_bet_won_path(html_options: { won: true, bet_id: bet.parlay_group || bet.id }), method: :patch, class: "c-button--success-outline c-bet-card__button" %>
  <%= button_to 'Loss', admin_bet_won_path(html_options: { won: false, bet_id: bet.parlay_group || bet.id }), method: :patch, class: "c-button--danger-outline c-bet-card__button" %>
</div>

app/views/shared/_cookie_consent_banner.html.erb
<div id="cookie-consent-banner-container" data-controller="cookies" data-cookies-target="cookieBanner" style="display: none;">
  <%= form_tag do |f| %>
    <div class="checkboxes-container">
      <div class="checkbox-container">
        <%= check_box_tag 'neccessary', value: true, checked: true, disabled: true, class: "form-input form-check-input" %>
        <%= label_tag 'neccessary', 'Neccessary' %>
      </div>

      <div class="checkbox-container">
        <%= check_box_tag 'marketing', id: 'marketing', class: "form-input form-check-input", data: { cookies_target: 'marketingConsent' } %>
        <%= label_tag 'marketing', 'Marketing' %>
      </div>

      <div class="checkbox-container">
        <%= check_box_tag 'analytics', class: "form-input form-check-input", data: { cookies_target: 'anyliticsConsent' } %>
        <%= label_tag 'analytics', 'Analytics' %>
      </div>
    </div>

    <div class="button-container">
      <%= button_tag 'Accept all', class: "c-button", data: { action: "click->cookies#acceptAllCookies"} %>
      <%= button_tag 'Accept selected', class: "c-button--outline", data: { action: "click->cookies#acceptPickedCookies"} %>
      <%= button_tag 'Reject all', class: "c-button--outline", data: { action: "click->cookies#denyAllCookies"} %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if flash[:notice] %>
  <div class="c-flash--success" id="flash">
    <% Array(flash[:notice]).each do |msg| %>
      <p><%= msg %></p>
    <% end %>
    <button class="c-button" onclick="closeFlash()"><%= icon('fa-solid', 'xmark') %></button>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="c-flash--alert" id="flash">
    <div>
      <h3>Please correct the following issues:</h5>
      <ul>
        <% Array(flash[:alert]).each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <button class="c-button" onclick="closeFlash()"><%= icon('fa-solid', 'xmark') %></button>
  </div>
<% end %>

<script>
  function closeFlash() {
    const flashMessage = document.getElementById("flash");
    flashMessage.remove()
  }
</script>

app/views/shared/_modal.html.erb
<div class="c-modal" id="modal" data-active="false" data-controller="modal" style="display: none;">
  <div>
    <% if type == "bets" %>
      <%= render "shared/modal_content_bets", bet: bet %>
    <% end %>
  </div>
</div>

app/views/shared/_modal_content_bets.html.erb
<h2>Are you sure you want to unlock this bet?</h1>
<div class="c-modal__c-buttons">
  <%= button_to 'Yes', admin_unlock_bet_path(bet), method: :patch, class: "c-button" %>
  <%= button_tag 'No', data: { action: "click->modal#hideModal" }, class: "c-button--outline" %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar" data-controller="navbar">
  <%= link_to root_path, class: "navbar__logo-link" do %>
    <%= image_tag 'logo_white.png', class: 'navbar__logo' %>
  <% end %>

  <div class="navbar__menu" data-navbar-target="menu">
    <%= link_to 'Home', root_path, class: "navbar__link" %>
    <%= link_to 'How it works', root_path(anchor: 'how-it-works'), class: "navbar__link" %>
    <%= link_to 'Pricing', pricing_path, class: "navbar__link" %>
    <% unless user_signed_in? %>
      <%= link_to "Sign up", new_user_registration_path, class: "c-button--outline" %>
    <% end %>
    <% if policy(Bet).index? %>
      <%= link_to "Picks", admin_bets_path, class: "c-button" %>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path, class: "c-button" %>
    <% end %>

    <div class="navbar__user-section">
      <% if user_signed_in? %>
        <% if current_user.premium %>
          <div class="navbar__credits"><%= icon('fa-solid', 'coins') %> <span class="u-highlight-prim">&infin;</span></div>
        <% else %>
          <div class="navbar__credits"><%= icon('fa-solid', 'coins') %> <span class="u-highlight-prim"><%= current_user.credits %></span></div>
        <% end %>
        <div class="navbar__user-dropdown" data-controller="user">
          <button class="navbar__user-toggle" data-action="click->user#toggle">
            <%= icon('fa-solid', 'user') %>
          </button>
          <div class="navbar__user-menu" data-user-target="menu">
            <div class="navbar__user-email"><span class="u-highlight-prim"><%= current_user.email %></span></div>
            <%= link_to 'Edit account', edit_user_registration_path(current_user), class: "navbar__user-menu-item" %>
            <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "navbar__user-menu-item" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <button class="navbar__toggle" data-action="click->navbar#toggleMenu" aria-label="Toggle menu">
    <%= icon('fa-solid', 'bars') %>
  </button>
</nav>

app/views/shared/_pick_and_parlay_card.html.erb
<div class="c-bet-card" id="bet_<%= bets.first.parlay_group || bets.first.id %>">
  <div class="c-bet-card__content">
    <div class="c-bet-card__body">
      <div class="c-bet-card__type-result">
        <h3><%= bet_type(bets.first) %></h3>
        <p class="c-bet-card__result <%= result_class(bets.first) %>"><%= result_text(bets.first) %></p>
      </div>

      <div class="c-bet-card__matches-grid">
        <% bets.each do |bet| %>
          <div class="c-bet-card__match-column">
            <p class="c-bet-card__bet-date"><%= bet.created_at.strftime('%e %b %Y') %></p>

            <% if policy(bet).view_data? %>
              <p class="c-bet-card__match-name u-highlight-prim"><%= bet.match.name %><br></p>
              <p class="c-bet-card__card-match-name u-highlight-prim"><%= bet.pick %><br></p>
              <p><strong>EU odds:</strong> <%= bet.eu_odds %> <span class="c-bet-card__separator">|</span> <strong>US Odds:</strong> <%= bet.us_odds %></p>
            <% else %>
              <p class="c-bet-card__match-name u-highlight-prim">Content hidden<br></p>
              <p><strong>EU odds:</strong> Content hidden <span class="c-bet-card__separator">|</span> <strong>US Odds:</strong> Content hidden</p>
            <% end %>
          </div>
          <% unless policy(bet).view_data? %>
            <div class="c-bet-card__cover" data-controller="modal">
              <%= icon("fa-solid", "lock") %>
              <%= button_tag 'Unlock bet', data: { action: "click->modal#showModal" }, class: "c-button" %>
              <%= render "shared/modal", type: "bets", bet: bet %>
            </div>
          <% end %>
        <% end %>
      </div>

      <% if bets.first.parlay_group %>
        <div>
          <p class="c-bet-card__total-odds">
            <% if policy(bets.first).view_data? %>
              <strong>Total Odds:</strong> <%= calculate_total_odds(bets) %>
            <% else %>
              <strong>Total Odds:</strong> Content hidden
            <% end %>
          </p>
        </div>
      <% end %>
    </div>

    <%= render 'shared/admin_buttons', bet: bets.first if current_user.admin? %>

  </div>

  <!-- Only show cover if data should not be visible -->
</div>