config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root 'pages#home'
  get 'membership', to: 'pages#membership'
  get 'contact', to: 'pages#contact'
  get 'cookie_consent', to: 'pages#cookie_consent'
  get 'pricing', to: 'pages#pricing'

  namespace :admin do
    resources :bets, except: %i[show]
    post 'bets/matches_autocomplete', to: 'bets#matches_autocomplete'
    post 'bets/:id/matches_autocomplete', to: 'bets#matches_autocomplete'
    patch 'bet_won', to: 'bets#bet_won', as: :bet_won
    post 'bets/:id/edit-bet-data', to: 'bets#edit_bet_data'
    post 'bets/send-daily-picks', to: 'bets#send_daily_picks'
    patch 'bets/:id/unlock_pick', to: 'bets#unlock_pick', as: :unlock_bet
  end

  namespace :stripe do
    get 'checkout', to: 'checkout#new'
    post 'get-client-secret', to: 'checkout#send_client_secret'
    get 'success', to: 'checkout#success'
    post 'subscribe-customer', to: 'checkout#create_subscription'
    post 'webhook', to: 'webhook#handle_webhook'
    post 'update-payment-method', to: 'checkout#update_payment_method'
  end

  namespace :postmark do
    post 'webhook', to: 'webhook#handle_webhook'
  end
end

app/views/pages/cookie_consent.html.erb
<div id="cookie-consent-container" data-controller="cookies">
  <%= form_tag do |f| %>
    <div class="checkboxes-container">
      <div class="checkbox-container">
        <%= check_box_tag 'neccessary', value: true, checked: true, disabled: true, class: "form-input form-check-input" %>
        <%= label_tag 'neccessary', 'Neccessary' %>
      </div>

      <div class="checkbox-container">
        <%= check_box_tag 'marketing', id: 'marketing', class: "form-input form-check-input", data: { cookies_target: 'marketingConsent' } %>
        <%= label_tag 'marketing', 'Marketing' %>
      </div>

      <div class="checkbox-container">
        <%= check_box_tag 'analytics', class: "form-input form-check-input", data: { cookies_target: 'anyliticsConsent' } %>
        <%= label_tag 'analytics', 'Analytics' %>
      </div>
    </div>

    <div class="button-container">
      <%= button_tag 'Accept all', class: "c-button", data: { action: "click->cookies#acceptAllCookies"} %>
      <%= button_tag 'Accept selected', class: "c-button--outline", data: { action: "click->cookies#acceptPickedCookies"} %>
      <%= button_tag 'Reject all', class: "c-button--outline", data: { action: "click->cookies#denyAllCookies"} %>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="c-home u-c-content">
  <!-- Main Section -->
  <section class="s-main">
    <div class="s-main__marketing-section">
      <h1>Unlock Daily Tennis Picks Backed by <span class="u-highlight-prim">Expert Research</span> and <span class="u-highlight-prim">AI Precision</span></h1>
      <p>
        Our team of experts and advanced AI deliver carefully curated tennis picks designed for consistent, steady returns.
        Join TennisWins today and elevate your betting strategy with insights you can trust.
      </p>
      <div class="s-main__cta-buttons">
        <%= link_to 'Sign up', new_user_registration_path, class: "c-button--outline" %>
        <%= link_to 'Picks', admin_bets_path, class: "c-button" %>
      </div>
    </div>

    <div class="s-main__picks-display">
      <div class="s-main__c-marketing">
        <h2>Won bets</h2>
        <h2 class="winning"><%= @number_won_bets %></h2>
      </div>
      <div class="s-main__c-marketing">
        <h2>Made for betters</h2>
        <h2 class="amount-made">$<%= @money_made %></h2>
      </div>
      <p class="u-base-calculation"># Calculated at $100 bet</p>
    </div>
  </section>

  <!-- How It Works Section -->
  <section class="s-how-works" data-controller="landing-page" id="how-it-works">
    <h2 class="u-section-title">How It Works</h2>
    <div class="s-how-works__c-how-works">
      <div class="s-how-works__c-steps">
        <p class="s-how-works__step active" id="step-1" data-action="click->landing-page#changeStep">Step 1 - Create a Free Account</p>
        <p class="s-how-works__step" id="step-2" data-action="click->landing-page#changeStep">Step 2 - Upgrade to Our Paid Membership</p>
        <p class="s-how-works__step" id="step-3" data-action="click->landing-page#changeStep">Step 3 - Receive Daily Picks</p>
      </div>
      <div class="s-how-works__c-step-desc">
        <p data-landing-page-target="stepDesc">
          Sign up with a free account to explore our historical data and gain access to our community channels on Discord/Telegram.
          See how our picks have performed over time and evaluate the quality of our insights.
        </p>
      </div>
    </div>
  </section>

  <!-- Why Us Section -->
  <section class="s-why-us">
    <h2 class="u-section-title">Why Choose Us?</h2>
    <div class="s-why-us__grid">
      <h3 class="s-why-us__example">Expert Insights & AI-Driven Analysis</h3>
      <p class="s-why-us__example">Our team of seasoned tennis experts conducts in-depth research on every matchup, considering player form, head-to-head records, and even personal factors. This human expertise is then enhanced by our advanced AI system, which cross-references data points to identify the highest probability outcomes.</p>

      <h3 class="s-why-us__example">Daily Picks Delivered to You</h3>
      <p class="s-why-us__example">Never miss an opportunity. Our picks are delivered straight to your inbox every morning and are also available in our members-only section, so you’re always ready to make your move.</p>

      <h3 class="s-why-us__example">Tailored for Serious Bettors</h3>
      <p class="s-why-us__example">We cater to those who are serious about making informed betting decisions. Whether you're placing $50 per pick or more, our service is designed to help you achieve long-term success.</p>

      <h3 class="s-why-us__example">Consistent, Reliable Picks</h3>
      <p class="s-why-us__example">We’re not about chasing high-risk, high-reward odds. Our picks focus on consistency, with odds typically around 2.00, offering you a balanced approach that’s designed to deliver steady returns over time.</p>
    </div>
  </section>

  <!-- Pricing Section -->
  <section class="s-pricing">
    <h2 class="u-section-title">Pricing</h2>
    <div class="s-pricing__c-pricing">
      <!-- Pricing Plan Unit -->
      <div class="s-pricing__plan">
        <h2>$14.99 / one time fee</h2>
        <div class="s-pricing__plan-feats">
          <ul>
            <li>Access to Historical Picks and Data</li>
            <li>Access to Discord / Telegram</li>
            <li>Access to Daily Picks in Members Section for that day</li>
            <li>You get 3 credits (1 credit = 1 bet)</li>
          </ul>
          <%= link_to 'Pick me!', stripe_checkout_path(prod_id: ENV.fetch('STRIPE_PR_ID_3_PICKS')), class: "c-button--outline" %>
        </div>
      </div>

      <div class="s-pricing__plan--monthly">
        <h2>$99.99 / monthly</h2>
        <div class="s-pricing__plan-feats">
          <ul>
            <li>Access to Historical Picks and Data</li>
            <li>Access to Discord / Telegram</li>
            <li>Access to Daily Picks in Members Section</li>
          </ul>
          <%= link_to 'Pick me!', stripe_checkout_path(prod_id: ENV.fetch('STRIPE_PR_ID_UNL_PICKS')), class: "c-button--outline" %>
        </div>
      </div>

      <div class="s-pricing__plan">
        <h2>$39.99 / one time fee</h2>
        <div class="s-pricing__plan-feats">
          <ul>
            <li>Access to Historical Picks and Data</li>
            <li>Access to Discord / Telegram</li>
            <li>Access to Daily Picks in Members Section for a week</li>
            <li>You get 15 credits (1 credit = 1 bet)</li>
          </ul>
          <%= link_to 'Pick me!', stripe_checkout_path(prod_id: ENV.fetch('STRIPE_PR_ID_15_PICKS')), class: "c-button--outline" %>
        </div>
      </div>
    </div>
  </section>

  <!-- Success Stories Section -->
  <section class="s-success-stories">
    <h2 class="u-section-title">Success Stories</h2>
    <p class="s-success-stories__subtitle">Below are some nice messages some of our team have received.</p>
    <div class="s-success-stories__grid">
      <% 6.times do %>
        <div></div>
      <% end %>
    </div>
    <%= link_to 'Sign up', new_user_registration_path, class: "c-button" %>
  </section>
</div>

app/views/pages/landing_page.html.erb
<!-- Divide sections -->

<div id="landing-page-c" class="content-c">

  <section id="main">
    <div class="marketing-slinty">
      <h1>Unlock Daily Tennis Picks Backed by <span class="highlight-prim">Expert Research</span> and <span class="highlight-prim">AI Precision</span></h1>
      <p>Our team of experts and advanced AI deliver carefully curated tennis picks designed for consistent, steady returns. Join TennisWins today and elevate your betting strategy with insights you can trust</p>
      <div class="cta-buttons">
        <%= link_to 'Picks', coming_soon_path, class: "button-prim" %>
        <%= link_to 'Sign up', coming_soon_path, class: "button-prim-outline" %>
      </div>
    </div>
    <div class="picks-display">
      <div class="winning-c">
        <h2 class="title-abs">Won bets</h2>
        <h2 class="winning">Coming soon!</h2>
      </div>
      <div class="amount-made-c">
        <h2 class="title-abs">Made for betters</h2>
        <h2 class="amount-made">Coming soon!</h2>
      </div>
      <p class="base-calculation-p"># Calculated with $100 bet</p>
    </div>
  </section>

  <section id="how-it-works" data-controller="landing-page">
    <h2 class="section-title">How It Works</h2>
    <div class="how-it-works-container">
      <div class="steps-container">
        <p class="step active" id="step-1" data-action="click->landing-page#changeStep">Step 1 - Create a Free Account</p>
        <p class="step" id="step-2" data-action="click->landing-page#changeStep">Step 2 - Upgrade to Our Paid Membership</p>
        <p class="step" id="step-3" data-action="click->landing-page#changeStep">Step 3 - Receive Daily Picks</p>
      </div>
      <div class="step-desc-container">
        <p class="step-desc" data-landing-page-target="stepDesc">Sign up with a free account to explore our historical data and gain access to our community channels on Discord/Telegram. See how our picks have performed over time and evaluate the quality of our insights.</p>
      </div>
    </div>
  </section>

  <section id="why-us">
    <h2 class="section-title">Why Choose Us?</h2>
    <div class="why-us-grid">
      <h3 class="w-u-item">Expert Insights & AI-Driven Analysis</h3>
      <p class="w-u-item">Our team of seasoned tennis experts conducts in-depth research on every matchup, considering player form, head-to-head records, and even personal factors. This human expertise is then enhanced by our advanced AI system, which cross-references data points to identify the highest probability outcomes.</p>

      <h3 class="w-u-item">Daily Picks Delivered to You</h3>
      <p class="w-u-item">Never miss an opportunity. Our picks are delivered straight to your inbox every morning and are also available in our members-only section, so you’re always ready to make your move.</p>

      <h3 class="w-u-item">Tailored for Serious Bettors</h3>
      <p class="w-u-item">We cater to those who are serious about making informed betting decisions. Whether you're placing $50 per pick or more, our service is designed to help you achieve long-term success.</p>

      <h3 class="w-u-item">Consistent, Reliable Picks</h3>
      <p class="w-u-item">We’re not about chasing high-risk, high-reward odds. Our picks focus on consistency, with odds typically around 2.00, offering you a balanced approach that’s designed to deliver steady returns over time.</p>
    </div>
  </section>

  <section id="pricing-section">
    <h2 class="section-title">Pricing</h2>
    <div id="pricing">
      <div class="free p-container">
        <h2>Free</h2>
        <ul>
          <li>Access to Historical Picks and Data</li>
          <li>Access to Discord / Telegram</li>
        </ul>
      </div>

      <div class="paid p-container">
        <h2>$99 / monthly</h2>
        <ul>
          <li>Access to Historical Picks and Data</li>
          <li>Access to Discord / Telegram</li>
          <li>Access to Daily Picks in Members Section</li>
          <li>Every Pick Emailed to You</li>
        </ul>
      </div>
    </div>

    <%= link_to 'Sign up', coming_soon_path, class: "button-prim" %>
  </section>

  <section id="success-stories">
    <h2 class="section-title">Success Stories</h2>
    <p class="subtitle">Below are some nice messages some of our team have received.</p>
    <div class="messages-grid">
      <div class="message-placeholder"></div>
      <div class="message-placeholder"></div>
      <div class="message-placeholder"></div>
      <div class="message-placeholder"></div>
      <div class="message-placeholder"></div>
      <div class="message-placeholder"></div>
    </div>
    <%= link_to 'Sign up', coming_soon_path, class: "button-prim button-prim-success-sec" %>
  </section>
</div>

app/views/pages/pricing.html.erb
<div class="c-pricing u-c-content">
  <h1>Pricing</h1>

  <div class="c-pricing__grid">
    <div class="c-pricing__plan">
      <h2>$14.99 / one time fee</h2>
      <div class="c-pricing__plan-feats">
        <ul>
          <li>Access to Historical Picks and Data</li>
          <li>Access to Discord / Telegram</li>
          <li>Access to Daily Picks in Members Section for that day</li>
          <li>You get 3 credits (1 credit = 1 bet)</li>
        </ul>
        <%= link_to 'Pick me!', stripe_checkout_path(prod_id: ENV.fetch('STRIPE_PR_ID_3_PICKS')), class: "c-button--outline" %>
      </div>
    </div>

    <div class="c-pricing__plan--monthly">
      <h2>$99.99 / monthly</h2>
      <div class="c-pricing__plan-feats">
        <ul>
          <li>Access to Historical Picks and Data</li>
          <li>Access to Discord / Telegram</li>
          <li>Access to Daily Picks in Members Section</li>
        </ul>
        <%= link_to 'Pick me!', stripe_checkout_path(prod_id: ENV.fetch('STRIPE_PR_ID_UNL_PICKS')), class: "c-button--outline" %>
      </div>
    </div>

    <div class="c-pricing__plan">
      <h2>$39.99 / one time fee</h2>
      <div class="c-pricing__plan-feats">
        <ul>
          <li>Access to Historical Picks and Data</li>
          <li>Access to Discord / Telegram</li>
          <li>Access to Daily Picks in Members Section for a week</li>
          <li>You get 15 credits (1 credit = 1 bet)</li>
        </ul>
        <%= link_to 'Pick me!', stripe_checkout_path(prod_id: ENV.fetch('STRIPE_PR_ID_15_PICKS')), class: "c-button--outline" %>
      </div>
    </div>
  </div>
</div>